name: CI

on:
    - push

jobs:
    unit-tests:
        name: Unit tests
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x, 16.x, 18.x, 19.x]

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: yarn --frozen-lockfile

            - name: Run unit tests
              run: yarn test

    code-quality:
        name: Code quality
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x, 16.x, 18.x, 19.x]

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: yarn --frozen-lockfile

            - name: Run unit tests
              run: yarn lint
